<?php

$sitemapServices = $this->sitemapServices;

?>		

<!-- ======== @Region: #highlighted ======== -->
		<div id="highlighted">
			<!-- Flexslider - May use standard Bootstrap markup within slides - For best results use images all the same size (in this example they are 600px x 400px) -->
			<!--Flexslider Showshow-->
			<section class="flexslider-wrapper container">
				<div class="flexslider" id="index-slider">
					<!--The Slides-->
					<div class="slides">
                                            
                                            <?php foreach ($this->enabledSlides as $slide) { ?>
                                             
                                            <div class="slide">
							<div class="row">
								<div class="col-sm-6">
									<img src="<?php echo $this->indexSlideImgUrl($slide); ?>" alt="<?php echo $this->escape($slide['title']); ?>" class="animated fadeInDownBig" />
								</div>
								<div class="col-sm-6 caption animated fadeInUpBig">
									<h2>
										<?php echo $this->escape($slide['title']); ?>
									</h2>
									<p>
										<?php echo $this->escape($slide['description']); ?>
									</p>
                                                                        
                                                                        <?php if($slide['link_type'] != 'NoLink'){ ?>
                                                                        
                                                                        <a target="_blank"
                                                                           href="<?php echo $this->indexSlideLinkUrl($slide); ?>" class="btn btn-lg btn-primary"><?php echo $this->escape($slide['link_label']); ?></a>
                                                                        
                                                                        <?php } ?>
								</div>
							</div>
						</div>
                                                
                                          <?php  } ?>

					</div>
				</div>
			</section>
		</div>

		<!-- ======== @Region: #content ======== -->
		<div id="content">
			<div class="container">
				<!-- Services -->
				<div class="block services margin-top-large">
					<h2 class="block-title">
						<span>Our Services</span> 
                                                
                                                <?php if ($this->sitemapServices) {?>
						<small><a href="<?php echo $this->sitemapPageUrl($this->sitemapServices['id']);?>">View all</a></small>
                                                <?php }?>
                                                
					</h2>
					<ul class="thumbnails row">
                                            
                                            <?php foreach ($this->services as $service) { ?>
                                                
                                            <li class="col-sm-3">
							<h3 class="title">
								<i class="<?php echo $service['icon'] ;?> icon-small icon-inverse-80 _icon-circle"></i> <?php echo $this->escape($service['title']) ; ?>
							</h3>
							<p><?php echo $this->escape($service['description']) ; ?></p>
						</li>
                                            
                                           <?php } ?>
                                            
					</ul>
				</div>
				<!-- portfolio -->
				<!-- Recommended screenshot size: 400px x 300px -->
				<div class="block portfolio margin-top-large">
					<h2 class="block-title">
						<span>Photo galleries</span> 
                                                <?php if ($this->photoGalleriesSitemapPage) {?>
						<small><a href="<?php echo $this->sitemapPageUrl($this->photoGalleriesSitemapPage['id']);?>">View all</a></small>
                                                <?php }?>
					</h2>
					<ul class="thumbnails row projects">
                                            
                                            <?php foreach ($this->photoGalleries as $photoGallery) { ?>
                                            
                                            <li class="col-md-4 ">
							<div class="">
								<div class="project">
									<a class="lnk-polaroid" href="<?php echo $this->photoGalleryUrl($photoGallery); ?>">
										<img src="<?php echo $this->photoGalleryLeadingPhotoUrl($photoGallery); ?>" alt="<?php echo $this->escape($photoGallery['title']); ?>" class="img-polaroid img-responsive" />
									</a>
									<h3 class="title">
										<a href="<?php echo $this->photoGalleryUrl($photoGallery); ?>"><?php echo $this->escape($photoGallery['title']); ?></a>
										<small class="pull-right"></small>
									</h3>
									<p class="muted"><?php echo $this->escape($photoGallery['description']); ?></p>
								</div>
							</div>
						</li>
                                            
                                            <?php } ?>
                                            
					</ul>
				</div>
			</div>
		</div>
<?php 
$this->headLink()->appendStylesheet($this->baseUrl('/plugins/flexslider/flexslider.css'));
$this->inlineScript()->appendFile($this->baseUrl('/plugins/flexslider/jquery.flexslider-min.js'));
?>
<script>
	<?php $this->inlineScript()->captureStart();?>
		$('#index-slider').flexslider({
			animation: 'slide',
			selector: '.slides > .slide',
			controlNav: true,
			smoothHeight: true,
			animationLoop: true,
			randomize: false,
                        startAt: 1
		});
	<?php $this->inlineScript()->captureEnd();?>
</script>