<?php $this->headTitle("Services"); ?>		

<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span>Services</span> 
						<small>The services we offer &amp; how we can help you!</small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container">
				<!-- Services -->
				<div class="block services">
					<ul class="thumbnails row">
                                            <?php foreach ($this->service as $service) { ?>
                                            
                                            	<li class="col-sm-12 col-md-3 col-lg-3">
							<h3 class="title">
								<i class="<?php echo $service['icon'] ;?> icon-small icon-inverse-80 _icon-circle"></i> <?php echo $this->escape($service['title']) ; ?>
							</h3>
							<p><?php echo $this->escape($service['description']) ; ?></p>
						</li>
                                            
                                            <?php    
                                            }
                                            ?>
					</ul>
					
				</div>
			</div>
		</div>