<?php

$sitemapPage = $this->sitemapPage;
//$this->headTitle('About Us');
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']);

?>		

<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span><?php echo $this->sitemapPage['title']; ?></span> 
						<small><?php echo $this->sitemapPage['description'] ;?></small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
                    <?php if($sitemapPage['body']) { ?>
		<div id="content">
                    <div class="container">
                        
                        <?php echo $sitemapPage['body'] ;?>
                        
                    </div>
                </div>    
                <?php } ?>
			<div class="container">
				<!-- Services -->
				<div class="block services">
					<ul class="thumbnails row">
                                            <?php foreach ($this->service as $service) { ?>
                                            
                                            	<li class="col-sm-12 col-md-3 col-lg-3">
							<h3 class="title">
								<i class="<?php echo $service['icon'] ;?> icon-small icon-inverse-80 _icon-circle"></i> <?php echo $this->escape($service['title']) ; ?>
							</h3>
							<p><?php echo $this->escape($service['description']) ; ?></p>
						</li>
                                            
                                            <?php    
                                            }
                                            ?>
					</ul>
					
				</div>
			</div>
		</div>