
<?php 

Zend_Layout::getMvcInstance()->disableLayout();

?>

<!DOCTYPE html>
<html>
<head></head>
<body>
	<h1>Choose your car brand/model</h1>
	<form action="" method="post">
		<p>
		<label>Brand</label>
		<select id="car-brand">
			<option value="">--- Choose Brand ---</option>
                        
		</select>
		</p>
		<p>
		<label>Model</label>
		<select id="car-model">
			<option value="">--- Choose Model ---</option>
		</select>
		</p>
	</form>
        <script src="<?php echo $this->baseUrl('/admin/bower_components/jquery/dist/jquery.min.js'); ?>"></script>   
        <script>
        
        $('#car-brand').on('change', function (e) {
            
           // e.preventDefault();
            e.stopPropagation();
            
            var target = $(this).is('#car-brand') ? $(this) : $(this).closest('#car-bran');
            
            var brand = target.val();
             
            var modelSelect = $('#car-model');

            // clear element inner html
            modelSelect.empty();
            modelSelect.append('<option value="">--- Choose Model ---</option>');

            
            if(brand) {
                
                $.ajax({
                    url: '<?php echo $this->url(array('controller' => 'admin_test', 'action' => 'ajaxmodels'), 'default', true); ?>',
                    data: {
                        "brand": brand
                    },
                   // method: "post", ovime setujemo metod. Po defaultu je get
                    cache: false 
                    
                }).done(function(data){
                   
                    for(var index in data){
                        
                        var model = data[index];
                        
                        var selectOption = $('<option></option>');
                        
                        selectOption.attr('value', model.value);
                
                        selectOption.text(model.label);
                
                        modelSelect.append(selectOption);
                    }
                    
                }).fail(function(){
                    
                    aleart('Unable to load models for brand');
                    
                }).always(function() {
                    
                });
            }
            
        });
        
        
        // $.ajax('/test.html', {});
        
        $.ajax({
            url: '<?php echo $this->url(array('controller' => 'admin_test', 'action' => 'ajaxbrands'), 'default', true); ?>',
            cache: false
    
        }).done(function(data, textStatus, jqXHR) {
            // on successful ajax page load
            
            for(var index in data) {
                
                var brand = data[index];
                
                var selectOption = $('<option></option>');
                
                selectOption.attr('value', brand.value);
                
                selectOption.html(brand.label);
                
                $('#car-brand').append(selectOption);
            }
            
        }).fail(function(jqXHR, textStatus, errorThrown ) {
            // on error while loading ajax page
            alert('Error occured while loading car brends');
            
        }).always(function() {
            // for action that do not depend on result
        });
        
        
        
        </script>
        
</body>
</html>
