<div class="page-header">
  <h1>JavaScript 1</h1>
</div>

<script>
   <?php $this->inlineScript()->captureStart();?>
    var ime = 'Milos';
    var starost = 30;
    
    //alert(ime);
     
    var polaznici = ["Pera Peric", "Zika Zikic", "Jovan Jovanovic"];
    
    for(var index in polaznici) {
       //console.log((parseInt(index)+1) + ": " + polaznici[index]); 
    }
    
    //console.log(polaznici);
    
    //alert(polaznici[1]);
    
    var polaznik = {
        ime: 'Ime1',
        prezime: 'Prezime1',
        starost: 30
    };
    
    
    for(var key in polaznik){
        //console.log(key  + " -> " + polaznik[key]);
    }
   // alert(polaznik.prezime);
    
    // JSON - Java Scrypt Object Notation
    
    var cubes = {
        name: 'Cubes d.o.o.',
        address: 'Bul Mih Pupina 181',
        courses: [
            {
                name: 'PHP',
                students: {
                    php01: 'Aleksandar Stevanovic',
                    php02: 'Natasa Lukic',
                    php03: 'Aleksandra Petkovic'
                }
            },
            {
                name: 'iOs',
                students: {
                    ios01: 'ios 1',
                    ios02: 'ios 2',
                    ios03: 'ios 3'
                }
            }
        ]
    };
    
  //  console.log(cubes);
   // alert(cubes.courses[0].students.php03);
    
   // alert(cubes['courses'][0]['students']['php02']);
   
   var doubleTestNumber = 77;
   
   function testF(testNumber){
       var doubleTestNumber = testNumber * 2;
       //console.log('Calling function testF ' + doubleTestNumber + '!');
   };
   
   testF(1); // calling function
   testF(2);
   testF(3);
   testF(4);
   testF(5);
   
   //console.log('Double test number is: ' + doubleTestNumber);
   
   var testF2 = function() {
       console.log('Calling testF2!')
   };
   
   testF2();
   
   // Object constructor
   function Polaznik(ime, prezime, starost) {
       
       this.ime = ime;
       this.prezime = prezime;
       this.starost = starost;
       
       this.predstaviSe = function() {
           return 'Ja sam ' + this.ime + ' ' + this.prezime + ' i imam ' + this.starost + ' god.';
       };
   };
   
   var p1 = new Polaznik('Ime1', 'Prezime1', 11);
   var p2 = new Polaznik('Ime2', 'Prezime2', 22);
   var p3 = new Polaznik('Ime3', 'Prezime3', 33);
   var p4 = new Polaznik('Ime4', 'Prezime4', 44);
   
   p4.getIme = function(){
       return this.ime;
   };
   
   console.log(p1.predstaviSe());
   console.log(p2.predstaviSe());
   console.log(p3.predstaviSe());
   console.log(p4.predstaviSe());
   
   // master objekat
   window;
   
   // working with computer screen
   window.screen;
   screen;
   
   // working with browser window location (address bar)
   window.location;
   location;
   
//   setTimeout(function() {
//       location.href = "http://www.google.com/";
//   }, 5000);
   
   // DOM
   window.document;
   document;
   <?php $this->inlineScript()->captureEnd();?>
</script>

