<div class="page-header">
  <h1>JavaScript 1</h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<button class="btn btn-default">Ulepsaj tabelu</button>
		<button class="btn btn-default">Dodaj red</button>
		<a href="http://www.facebook.com" class="btn btn-default">Otvori facebook</a>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<table>
			<thead>
				<tr>
					<th>ID</th>
					<th>Ime</th>
					<th>Prezime</th>
					<th>#</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>php01</td>
					<td>Aleksandar</td>
					<td>Stevanovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php02</td>
					<td>Natasa</td>
					<td>Lukic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php03</td>
					<td>Aleksandra</td>
					<td>Petkovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php04</td>
					<td>Djordje</td>
					<td>Stojiljkovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php05</td>
					<td>Milos</td>
					<td>Stefanovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php06</td>
					<td>Milomir</td>
					<td>Dragovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php07</td>
					<td>Miroslav</td>
					<td>Mutic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php08</td>
					<td>Bojan</td>
					<td>Joncic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php09</td>
					<td>Arben</td>
					<td>Bakiu</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php10</td>
					<td>Zeljka</td>
					<td>Babic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<script>
    var ime = 'Milos';
    var starost = 30;
    
    //alert(ime);
     
    var polaznici = ["Pera Peric", "Zika Zikic", "Jovan Jovanovic"];
    
    for(var index in polaznici) {
       //console.log((parseInt(index)+1) + ": " + polaznici[index]); 
    }
    
    //console.log(polaznici);
    
    //alert(polaznici[1]);
    
    var polaznik = {
        ime: 'Ime1',
        prezime: 'Prezime1',
        starost: 30
    };
    
    
    for(var key in polaznik){
        console.log(key  + " -> " + polaznik[key]);
    }
   // alert(polaznik.prezime);
    
    // JSON - Java Scrypt Object Notation
    
    var cubes = {
        name: 'Cubes d.o.o.',
        address: 'Bul Mih Pupina 181',
        courses: [
            {
                name: 'PHP',
                students: {
                    php01: 'Aleksandar Stevanovic',
                    php02: 'Natasa Lukic',
                    php03: 'Aleksandra Petkovic'
                }
            },
            {
                name: 'iOs',
                students: {
                    ios01: 'ios 1',
                    ios02: 'ios 2',
                    ios03: 'ios 3'
                }
            }
        ]
    };
    
  //  console.log(cubes);
   // alert(cubes.courses[0].students.php03);
    
   // alert(cubes['courses'][0]['students']['php02']);
</script>
