
<?php 

$this->headTitle('Services - Edit Service');

$form = $this->form;

$form->setElementDecorators(array('ViewHelper'));

?>

<div class="page-header">
    <h1>Services <small>Edit Service</small></h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'index'), 'default', true); ?>" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i> Back to all services</a>
                </div>  
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="">
                    <input type="hidden" name="task" value="update_service">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Service - <?php echo $this->escape($this->service['title']); ?></legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="title">Title</label>  
                            <div class="col-md-4">
                                <?php
                                echo $form->getElement('title')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter the title name',
                                    'id' => 'title',
                                    'required' => 'required'
                                ));
                                ?>
                                <span class="help-block">min 2 max 255 characters</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('title')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('title')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="icon">Icon</label>  
                            <div class="col-md-4">
                                 <?php
                                echo $form->getElement('icon')->setAttribs(array(
                                    'class' => 'form-control input-md',
                                    'placeholder' => 'enter icon\'s class',
                                    'id' => 'icon',
                                    'required' => 'required'
                                ));
                                ?>
                                <span class="help-block">i.e. "fa fa-eye..."</span>  
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('icon')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('icon')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="description">Description</label>
                            <div class="col-md-4">      
                                 <?php
                                echo $form->getElement('description')->setAttribs(array(
                                    'class' => 'form-control',
                                    'id' => 'description',
                                    'required' => 'required',
                                    'rows' => 12,
                                ));
                                ?>
                               
                            </div>
                            <div class="col-md-4">
                                <?php if ($form->getElement('description')->hasErrors()) { ?>
                                    <div class="has-error">
                                        <?php foreach ($form->getElement('description')->getMessages() as $message) { ?>
                                            <p class="help-block"><?php echo $this->escape($message); ?></p>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="update_service_cancel"></label>
                            <div class="col-md-4 text-right">
                                <a href="<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'index'), 'default', true); ?>" id="new_member_cancel" name="new_member_cancel" class="btn btn-default">Cancel</a>
                                <button type="submit" id="new_member_submit" name="update_service_submit" class="btn btn-success">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

