
<?php 

$this->headTitle('Services');

?>

<div class="page-header">
    <h1>Services</h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'add'), 'default', true); ?>" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i> Add service</a>
                </div>  
            </div>
            <div class="panel-body">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">Icon</th>
                            <th class="text-center">Status</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->services as $service){
                            
                            if($service['status'] == Application_Model_DbTable_CmsServices::STATUS_DISABLED){
                                ?>
                        <tr class="danger">
                            <td class="text-center"><i class="<?php echo $service['icon'] ;?>"></i></td>
                            <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                            <td><?php echo $this->escape($service['title']); ?></td>
                            <td><span data-toggle="popover" data-placement="top" data-container="body" data-content="<?php echo $this->escape($service['description']); ?>"><?php echo $this->escape(mb_substr($service['description'], 0, 20) . "..."); ?></span></td>
                            <td class="text-center">
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'edit', 'id' => $service['id']), 'default', true); ?>"
                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <button type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                </div>
                            </td>
                        </tr>
                            
                        <?php
                            } else{
                            ?>
                          <tr>
                            <td class="text-center"><i class="<?php echo $service['icon'] ;?>"></i></td>
                            <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                            <td><?php echo $this->escape($service['title']); ?></td>
                            <td><span data-toggle="popover" data-placement="top" data-container="body" data-content="<?php echo $this->escape($service['description']); ?>"><?php echo $this->escape(mb_substr($service['description'], 0, 20) . "..."); ?></span></td>
                           <td class="text-center">
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'edit', 'id' => $service['id']), 'default', true); ?>"
                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <button type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                </div>
                            </td>
                        </tr>
                        
                        <?php
                            }
                        } 
                        ?>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>