
<?php 

$this->headTitle('Members - Edit Member');

?>

<div class="page-header">
    <h1>Members <small>Edit Member</small></h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'index'), 'default', true); ?>" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-arrow-left"></i> Back to all members</a>
                </div>  
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="">
                    <input type="hidden" name="task" value="edit_member">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Member</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="first_name">First name</label>  
                            <div class="col-md-4">
                                <input id="first_name" name="first_name" placeholder="enter member's first name" class="form-control input-md" required="" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="last_name">Last Name</label>  
                            <div class="col-md-4">
                                <input id="last_name" name="last_name" placeholder="enter member's last name" class="form-control input-md" required="" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="email">Email</label>  
                            <div class="col-md-4">
                                <input id="email" name="email" placeholder="enter member's email" class="form-control input-md" required="" type="text">
                                <span class="help-block">username@dimain</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="work_title">Work Title</label>  
                            <div class="col-md-4">
                                <input id="work_title" name="work_title" placeholder="enter member's work title" class="form-control input-md" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Textarea -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="resume">Resume</label>
                            <div class="col-md-4">                     
                                <textarea class="form-control" id="resume" name="resume"></textarea>
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="edit_member_cancel"></label>
                            <div class="col-md-8">
                                <button id="new_member_cancel" name="edit_member_cancel" class="btn btn-default">Cancel</button>
                                <button id="new_member_submit" name="edit_member_submit" class="btn btn-success">Save</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
