<?php 

$this->headTitle('Members');

?>

<div class="page-header">
    <h1>Members</h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'add'), 'default', true); ?>" 
                        class="btn btn-default"
                        ><i class="glyphicon glyphicon-plus"></i> Add member</a>
                </div>  
            </div>
            <div class="panel-body">
                <table id="rows-table" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">Img</th>
                            <th class="text-center">Status</th>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Work Title</th>
                            <th>Email</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->members as $member){
                            
                            if($member['status'] == Application_Model_DbTable_CmsMembers::STATUS_DISABLED){
                                ?>
                        <tr class="danger">
                            <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->memberImgUrl($member); ?>"></td>
                             <td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
                            <td><?php echo $this->escape($member['first_name']); ?></td>
                            <td><?php echo $this->escape($member['last_name']); ?></td>
                            <td><?php echo $this->escape($member['work_title']); ?></td>
                            <td><?php echo $this->escape($member['email']); ?></td>
                            <td class="text-center">
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'aboutus', 'action' => 'member', 'id' => $member['id']), 'default', true); ?>"
                                        target="_blank"
                                        type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'edit', 'id' => $member['id']), 'default', true); ?>"
                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <button data-memberId="<?php echo $this->escape($member['id']); ?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                    <button data-memberId="<?php echo $this->escape($member['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                </div>
                            </td>
                        </tr>
                            
                        <?php
                            } else{
                            ?>
                          <tr>
                            <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->memberImgUrl($member); ?>"></td>
                            <td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
                            <td><?php echo $this->escape($member['first_name']); ?></td>
                            <td><?php echo $this->escape($member['last_name']); ?></td>
                            <td><?php echo $this->escape($member['work_title']); ?></td>
                            <td><?php echo $this->escape($member['email']); ?></td>
                            <td class="text-center">
                                <div class="btn-group btn-group-sm" role="group" aria-label="...">
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'aboutus', 'action' => 'member', 'id' => $member['id']), 'default', true); ?>"
                                        target="_blank"
                                        type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
                                    <a 
                                        href="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'edit', 'id' => $member['id']), 'default', true); ?>"
                                        type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <button data-memberId="<?php echo $this->escape($member['id']); ?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                    <button data-memberId="<?php echo $this->escape($member['id']); ?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
                                </div>
                            </td>
                        </tr>
                        
                        <?php
                            }
                        } 
                        ?>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'delete'), 'default', true);?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete member</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete member?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'disable'), 'default', true);?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable member</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to disable member?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i> Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<form method="post" action="<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'enable'), 'default', true);?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enable member</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to enable member?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-check"></i> Enable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->
<script>
<?php $this->inlineScript()->captureStart(); ?>

$('#rows-table').on('click', '[data-action="delete"]', function(e) {
    e.preventDefault();
    e.stopPropagation();
    
    var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');
    
    var memberId = target.attr('data-memberId');
      // get data- attributs
     // var memberId = target.data('memberId');
    
    
    $('#delete-warning-dialog').find('[name="id"]').val(memberId);
    
    
    $('#delete-warning-dialog').modal('show');
    
    
});

$('#rows-table').on('click', '[data-action="disable"]', function(e) {
    e.preventDefault();
    e.stopPropagation();
    
    var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
    
    var memberId = target.attr('data-memberId');
      // get data- attributs
     // var memberId = target.data('memberId');
    
    
    $('#disable-warning-dialog').find('[name="id"]').val(memberId);
    
    
    $('#disable-warning-dialog').modal('show');
    
    
});

$('#rows-table').on('click', '[data-action="enable"]', function(e) {
    e.preventDefault();
    e.stopPropagation();
    
    var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');
    
    var memberId = target.attr('data-memberId');
      // get data- attributs
     // var memberId = target.data('memberId');
    
    
    $('#enable-warning-dialog').find('[name="id"]').val(memberId);
    
    
    $('#enable-warning-dialog').modal('show');
    
    
});

<?php $this->inlineScript()->captureEnd(); ?>
</script>