<?php

$this->headTitle('Users');

?>
<div class="page-header">
  <h1>Users</h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<?php echo $this->systemMessagesHtml($this->systemMessages);?>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading text-right">
				<div class="btn-group" role="group" aria-label="...">
					<a 
						href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'add'), 'default', true);?>"
						class="btn btn-default"
						><i class="glyphicon glyphicon-plus"></i> Add user</a>
				</div>
			</div>
			<div class="panel-body">
				
				<table id="rows-table" class="table table-striped table-hover">
					<thead>
						<tr>
							<th class="text-center">Status</th>
							<th>Username</th>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
						<?php 
						foreach ($this->users as $user) {
							if ($user['status'] == Application_Model_DbTable_CmsUsers::STATUS_DISABLED) {
							?>
						<tr data-user-id="<?php echo $this->escape($user['id']);?>" class="danger">
							<td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
							<td><?php echo $this->escape($user['username']);?></td>
							<td><?php echo $this->escape($user['first_name']);?></td>
							<td><?php echo $this->escape($user['last_name']);?></td>
							<td><?php echo $this->escape($user['email']);?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
										href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
										type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
									<button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								
								</div>
							</td>
						</tr>
							<?php
							} else {
							?>
						<tr data-user-id="<?php echo $this->escape($user['id']);?>">
							<td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
							<td><?php echo $this->escape($user['username']);?></td>
							<td><?php echo $this->escape($user['first_name']);?></td>
							<td><?php echo $this->escape($user['last_name']);?></td>
							<td><?php echo $this->escape($user['email']);?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
									<a 
										href="<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'edit', 'id' => $user['id']), 'default', true);?>"
										type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-remove"></i></button>
									<button data-user-id="<?php echo $this->escape($user['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								
								</div>
							</td>
						</tr>
							<?php
							}
							?>
						
							<?php
						}
						?>
						
					</tbody>
				</table>
				
				
				
			</div>
		</div>
	</div>
</div>