
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<?php echo $this->headTitle('Cubes School')->setSeparator(' | '); ?>
                
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- @todo: fill with your company info or remove -->
		<meta name="description" content="">
		<meta name="author" content="Cubes School">
		<!-- Bootstrap CSS -->
		<link href="<?php echo $this->baseUrl('/plugins/bootstrap/dist/css/bootstrap.min.css'); ?>" rel="stylesheet">
		<!-- Font Awesome CSS -->
		<link href="<?php echo $this->baseUrl('/plugins/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet">
		<!-- Theme style -->
		<link href="<?php echo $this->baseUrl('/css/theme-style.css'); ?>" rel="stylesheet">
		<!-- Your custom override -->
		<link href="<?php echo $this->baseUrl('/css/custom-style.css'); ?>" rel="stylesheet">
		<!-- @option: Colour skins, choose from: 1. colour-blue.css 2. colour-red.css 3. colour-grey.css 4. colour-purple 5. colour-green.css Uncomment line below to enable -->
		<link href="<?php echo $this->baseUrl('/css/colour-blue.css'); ?>" rel="stylesheet" id="colour-scheme">
		
                 <?php echo $this->headLink();?>
                
                <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="<?php echo $this->baseUrl('/plugins/html5shiv/dist/html5shiv.js'); ?>"></script>
		<script src="<?php echo $this->baseUrl('/plugins/respond/respond.min.js'); ?>"></script>
		<![endif]-->
                
                <?php echo $this->headScript(); ?>
                
		<!-- Le fav and touch icons - @todo: fill with your icons or remove -->
		<link rel="shortcut icon" href="/img/favicons/96x96.png">
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $this->baseUrl('/img/favicons/114x114.png'); ?>">
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $this->baseUrl('/img/favicons/72x72.png'); ?>">
		<link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl('/img/favicons/96x96.png'); ?>">
		<link href='https://fonts.googleapis.com/css?family=Monda:400,700' rel='stylesheet' type='text/css'>
	</head>

	<!-- ======== @Region: body ======== -->
	<body class="has-navbar-fixed-top has-highlighted">

		<!-- ======== @Region: #navigation ======== -->
		<div id="navigation" class="wrapper">
			<!--Branding & Navigation Region-->
			<div class="navbar navbar-fixed-top" id="top">
				<div class="navbar-inner">
					<div class="inner">
						<div class="container">
							<div class="navbar-header">
								<button type="button" class="navbar-toggle btn btn-navbar" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
								<a class="navbar-brand" href="<?php echo $this->baseUrl('/'); ?>" title="Home">
									<h1>
										Framework
									</h1>
									<span>Cubes School</span> 
								</a>
							</div>
							<div class="collapse navbar-collapse">
								<ul class="nav navbar-right" id="main-menu">
									<li>
										<a href="<?php echo $this->baseUrl('/'); ?>">Home</a>
									</li>
                                                                        
                                                                        <li>
										<a href="<?php echo $this->baseUrl('/services'); ?>">Services</a>
									</li>
                                                                        
                                                                        <li>
										<a href="/aboutus">About Us</a>
									</li>
                                                                        
                                                                         <li>
										<a href="/contact"> Contact</a>
									</li>
                                                                        
									<li>
										<a href="<?php echo $this->baseUrl('/admin_dashboard/index'); ?>"><i class="fa fa-user"></i> Login</a>
									</li>
								</ul>
							</div>
							<!--/.nav-collapse -->
						</div>
					</div>
				</div>
			</div>
		</div>

		
                <?php echo $this->layout()->content; ?>
                
		<!-- FOOTER -->

		<!-- ======== @Region: #footer ======== -->
		<footer id="footer">
			<div class="container">
				<div class="row">
					<!--@todo: replace with company copyright details-->
					<div class="subfooter">
						<div class="col-md-5">
							<p><a href="http://school.cubes.rs/">Cubes School</a> | Copyright 2016 &copy;</p>
						</div>
						<div class="col-md-7 col social-media">
							<!--@todo: replace with company social media details-->
							<a href="#"><i class="fa fa-twitter"></i> Twitter</a>
							<a href="#"><i class="fa fa-facebook"></i> Facebook</a>
							<a href="#"><i class="fa fa-linkedin"></i> LinkedIn</a>
							<a href="#"><i class="fa fa-google-plus"></i> Google +</a>
						</div>
					</div>
				</div>
				<div class="row">
					<!--@todo: replace with company copyright details-->
					<div class="subfooter">
						
					</div>
				</div>
			</div>
		</footer>
		<!--Scripts -->
		<script src="<?php echo $this->baseUrl('/js/jquery.js'); ?>"></script>
		<!-- Bootstrap Javascript -->
		<script src="<?php echo $this->baseUrl('/plugins/bootstrap/dist/js/bootstrap.min.js'); ?>"></script>
                <?php echo $this->inlineScript();?>
        </body>

</html>