

<?php 

$this->headTitle('Profile - Edit Profile');

?>

<div class="page-header">
    <h1>Profile <small>Edit Profile</small></h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <?php echo $this->systemMessagesHtml($this->systemMessages);?>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <a 
                        href="<?php echo $this->url(array('controller' => 'admin_profile', 'action' => 'changepassword'), 'default', true); ?>" 
                        class="btn btn-default"
                        ><i class="fa fa-key"></i> Change Password</a>
                </div>  
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="post" action="">
                    <input type="hidden" name="task" value="edit_profile">
                    <fieldset>

                        <!-- Form Name -->
                        <legend>Edit Profile</legend>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="first_name">First name</label>  
                            <div class="col-md-4">
                                <input id="first_name" name="first_name" placeholder="enter member" class="form-control input-md" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="last_name">Last Name</label>  
                            <div class="col-md-4">
                                <input id="last_name" name="last_name" placeholder="enter member" class="form-control input-md" type="text">
                                <span class="help-block">min 3 max 255 characters</span>  
                            </div>
                        </div>

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="email">Email</label>  
                            <div class="col-md-4">
                                <input id="email" name="email" placeholder="enter member's email" class="form-control input-md" type="text">
                                <span class="help-block">username@dimain</span>  
                            </div>
                        </div>

                        <!-- Button (Double) -->
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="edit_profile_cancel"></label>
                            <div class="col-md-8">
                                <button id="edit_profile_cancel" name="edit_profile_cancel" class="btn btn-default">Cancel</button>
                                <button id="edit_profile_submit" name="edit_profile_submit" class="btn btn-success">Save</button>
                            </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
