<?php 
 

$member = $this->member;
$this->headTitle("Contact " . $member['first_name'] . ' ' . $member['last_name']); 


?>

<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span>Contact <?php echo $this->escape($member['first_name']. ' ' . $member['last_name']); ?></span> 
						<small>No project too big or small, get in touch!</small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container">
				<div class="block">
					<div class="row">
						<div class="col-sm-6">
                                                    <div class="row team-member">
                                                        <div class="col-sm-3" style="padding-bottom: 20px;">
								<img alt="<?php echo $this->escape($member['first_name']); ?>" class="img-polaroid" src="<?php echo $this->memberImgUrl($member); ?>">
                                                                
							</div>
							<div class="col-sm-9">
								<h3>
									<?php echo $this->escape($member['first_name'] . ' ' . $member['last_name']); ?>
								</h3>
								
							</div>
						</div>
							<form action="#" id="contact-form">
								<div class="form-group">
									<input type="text" placeholder="Name" class="form-control">
								</div>
								<div class="form-group">
									<input type="email" placeholder="Email" class="form-control">
								</div>
								<div class="form-group">
									<textarea placeholder="Message" class="form-control" rows="15"></textarea>
								</div>
								<input type="button" value="Send Message" class="btn btn-primary">
							</form>
						</div>
						<div class="col-sm-6">
							<h3 class="block-title sub-title">
								<span>Other Ways To Get In Touch</span>
							</h3>
							<p><abbr title="Phone">P</abbr>: 011/3210-112</p>
							<p><abbr title="Fax">F</abbr>: 011/3210-112</p>
							<p><abbr title="Email">E</abbr>: office@cubes.rs</p>
							<p><abbr title="Address">A</abbr>: Bulevar Milutina Milankovića 181, 11000 Beograd</p>
							<a href="https://maps.google.co.uk/maps?q=London&amp;ie=UTF8&amp;hq=&amp;hnear=London,+United+Kingdom&amp;gl=uk&amp;t=m&amp;ll=51.510238,-0.127029&amp;spn=0.042735,0.102654&amp;z=12&amp;">
								<img class="img-polaroid" alt="Location map" src="/img/misc/map.png">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>