<?php

$sitemapPage = $this->sitemapPage;
//$this->headTitle('About Us');
$this->headTitle($sitemapPage['title']);
$this->headMeta()->appendName('description', $sitemapPage['description']);

?>

<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span><?php echo $this->sitemapPage['title']; ?></span> 
						<small><?php echo $this->sitemapPage['description'] ;?></small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container">
				<div class="block">
					<div class="row">
						<div class="col-sm-6">
							<form action="#" id="contact-form">
								<div class="form-group">
									<input type="text" placeholder="Name" class="form-control">
								</div>
								<div class="form-group">
									<input type="email" placeholder="Email" class="form-control">
								</div>
								<div class="form-group">
									<textarea placeholder="Message" class="form-control" rows="15"></textarea>
								</div>
								<input type="button" value="Send Message" class="btn btn-primary">
							</form>
						</div>
						<div class="col-sm-6">
                                                    
                                                    <?php echo $this->sitemapPage['body'] ;?>
                                                    

						</div>
					</div>
				</div>
			</div>
		</div>